### ISSUE TITLE
step_calculate_entropy

### ISSUE THREAD

**Issue by alexmondaini** [YeoLab/eclip#20]
Hi Brian,

I'm having an issue for a particular sample I'm running. Here is the log:

```
INFO [job step_calculate_entropy] /tmp/pbs.695680.xomics/8mp720nb$ singularity \
    --quiet \
    exec \
    --contain \
    --pid \
    --ipc \
    --home \
    /tmp/pbs.695680.xomics/8mp720nb:/MnBdev \
    --bind \
    /tmp/pbs.695680.xomics/m21a5pc9:/tmp:rw \
    --bind \
    /tmp/pbs.695680.xomics/vz8cyndr/Akshay.ep_MN_R2.A01.r1.fq.genome-mappedSo.rmDupSo.merged.r2.peakClusters.normed.bed.full:/var/lib/cwl/stg6f233d80-e6f9-4da4-8fe4-10572c870b30/Akshay.ep_MN_R2.A01.r1.fq.genome-mappedSo.rmDupSo.merged.r2.peakClusters.normed.bed.full:ro \
    --bind \
    /tmp/pbs.695680.xomics/e2c4al7x/input_mapped_readnum.txt:/var/lib/cwl/stg33c7a395-e869-4168-bc04-afcc97c7e484/input_mapped_readnum.txt:ro \
    --bind \
    /tmp/pbs.695680.xomics/aofadwex/ip_mapped_readnum.txt:/var/lib/cwl/stgb2bcc05c-7fd3-4ed5-939e-ab8d57c6c7c2/ip_mapped_readnum.txt:ro \
    --pwd \
    /MnBdev \
    /groups/cgsd/alexandre/eclip/workflow/brianyee_eclip:0.7.0_python.sif \
    calculate_entropy.py \
    --output \
    Akshay.ep_MN_R2.A01.r1.fq.genome-mappedSo.rmDupSo.merged.r2.peakClusters.normed.bed.entropynum \
    --full \
    /var/lib/cwl/stg6f233d80-e6f9-4da4-8fe4-10572c870b30/Akshay.ep_MN_R2.A01.r1.fq.genome-mappedSo.rmDupSo.merged.r2.peakClusters.normed.bed.full \
    --ip_mapped \
    /var/lib/cwl/stgb2bcc05c-7fd3-4ed5-939e-ab8d57c6c7c2/ip_mapped_readnum.txt \
    --input_mapped \
    /var/lib/cwl/stg33c7a395-e869-4168-bc04-afcc97c7e484/input_mapped_readnum.txt
WARNING: Overriding HOME environment variable with SINGULARITYENV_HOME is not permitted
Traceback (most recent call last):
  File "/opt/eclip/bin/calculate_entropy.py", line 96, in <module>
    main()
  File "/opt/eclip/bin/calculate_entropy.py", line 87, in main
    l2fc=l2fc
  File "/opt/eclip/bin/calculate_entropy.py", line 34, in sum_entropy
    peaks['entropy'] = peaks.apply(entropy, args=(ip_mapped_num, input_mapped_num, ), axis=1)
  File "/opt/conda/lib/python2.7/site-packages/pandas/core/frame.py", line 3370, in __setitem__
    self._set_item(key, value)
  File "/opt/conda/lib/python2.7/site-packages/pandas/core/frame.py", line 3444, in _set_item
    self._ensure_valid_index(value)
  File "/opt/conda/lib/python2.7/site-packages/pandas/core/frame.py", line 3426, in _ensure_valid_index
    raise ValueError('Cannot set a frame with no defined index '
ValueError: Cannot set a frame with no defined index and a value that cannot be converted to a Series
ERROR [job step_calculate_entropy] Job error:
("Error collecting output for parameter 'output_entropynum':\ncwl/calculate_entropy.cwl:53:7: Did not find output file with glob pattern: '['Akshay.ep_MN_R2.A01.r1.fq.genome-mappedSo.rmDupSo.merged.r2.peakClusters.normed.bed.entropynum']'", {})
WARNING [job step_calculate_entropy] completed permanentFail
ERROR [step step_calculate_entropy] Output is missing expected field file:///groups/cgsd/alexandre/eclip/workflow/cwl/wf_get_peaks_pe.cwl#step_calculate_entropy/output_entropynum
```

I think most importantly from this log is the python pandas issue:

`ValueError: Cannot set a frame with no defined index and a value that cannot be converted to a Series`. thanks

**Comment by byee4** [comment]
Hi, can you let me know how many peaks you're calculating the entropy value over? The error looks like there are no significant peaks in the BED file

**Comment by alexmondaini** [comment]
Hi,

The bed file Akshay.ep_MN_R2.H0.r1.fq.genome-mappedSo.rmDupSo.merged.r2.peakClusters.normed.bed has 169 intervals, those are my peaks correct ? 

I would also like to ask one different question aside of this topic. I essentially don't need the PCR duplicate removal step , is it enough if I set the randomer_lenght to 0 in the pair_end.yaml file ?  or do I need to manually change the cwl file so as to skip the pcr duplicate rmeoval step ? thanks a lot.

**Comment by byee4** [comment]
Hi yes, those are your peaks, would you be able to filter for significant peaks only (the fourth and fifth columns contain the -log10(p-value) and log2(fold over SMInput))? I believe the threshold is set to 3 and 3, which is the recommended cutoff for significance calculations. 

I haven't tried this, but I would guess that you can try setting the randomer to be longer (at the cost of a shorter read) would mean less collisions? Otherwise yes, you would need to hack https://github.com/YeoLab/eclip/blob/master/cwl/wf_trim_and_map_pe.cwl a bit to skip the dup removal.

**Comment by alexmondaini** [comment]
yeah that's right, empty dataframe:

```
data = pd.read_csv('./Akshay.ep_MN_R2.H0.r1.fq.genome-mappedSo.rmDupSo.merged.r2.peakClusters.normed.bed',sep='\t',header=None)
print(data.head())
print( data[ (data[3]>=3) & (data[4]>=3) ] )
```

**Comment by alexmondaini** [comment]
I'm also having a lot of warnings when the pipeline starts , wonder is there is any chance something wrong is happening downstream because of so many warnings. I'm using `cwltool 3.0.20200706173533` as you recommended.

```
singularity/3.7.2 is loaded 
[1;30mINFO[0m /groups/cgsd/alexandre/miniconda3/envs/bioalex/bin/cwltool 3.0.20200706173533
[1;30mINFO[0m Resolved '/groups/cgsd/alexandre/eclip/workflow/cwl/wf_get_peaks_scatter_pe.cwl' to 'file:///groups/cgsd/alexandre/eclip/workflow/cwl/wf_get_peaks_scatter_pe.cwl'
Could not load extension schema http://schema.org/docs/schema_org_rdfa.html: Error fetching http://schema.org/docs/schema_org_rdfa.html: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
Warning: Field `$schemas` contains undefined reference to `http://schema.org/docs/schema_org_rdfa.html`
cwl/samtools-index.cwl:54:3: Warning: Field `class` contains undefined reference to
                             `http://schema.org/CreativeWork`
cwl/samtools-index.cwl:69:7: Warning: checking item
                             Warning:   Field `class` contains undefined reference to
                             `http://schema.org/Organization`
cwl/samtools-index.cwl:65:5: Warning: checking item
                             Warning:   Field `class` contains undefined reference to
                             `http://schema.org/Organization`
cwl/samtools-index.cwl:59:3: Warning: Field `class` contains undefined reference to
                             `http://schema.org/Person`
Could not load extension schema http://schema.org/docs/schema_org_rdfa.html: Error fetching http://schema.org/docs/schema_org_rdfa.html: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
Warning: Field `$schemas` contains undefined reference to `http://schema.org/docs/schema_org_rdfa.html`
cwl/samtools-index.cwl:54:3: Warning: Field `class` contains undefined reference to
                             `http://schema.org/CreativeWork`
cwl/samtools-index.cwl:69:7: Warning: checking item
                             Warning:   Field `class` contains undefined reference to
                             `http://schema.org/Organization`
cwl/samtools-index.cwl:65:5: Warning: checking item
                             Warning:   Field `class` contains undefined reference to
                             `http://schema.org/Organization`
cwl/samtools-index.cwl:59:3: Warning: Field `class` contains undefined reference to
                             `http://schema.org/Person`
Could not load extension schema http://schema.org/docs/schema_org_rdfa.html: Error fetching http://schema.org/docs/schema_org_rdfa.html: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
Warning: Field `$schemas` contains undefined reference to `http://schema.org/docs/schema_org_rdfa.html`
cwl/star-genome.cwl:1468:5: Warning: Field `class` contains undefined reference to
                            `http://schema.org/SoftwareApplication`
cwl/star-genome.cwl:1473:5: Warning: checking object
                            `http://dx.doi.org/10.1093/bioinformatics/bts635`
                            Warning:   Field `class` contains undefined reference to
                            `http://schema.org/ScholarlyArticle`
cwl/star-genome.cwl:1483:7: Warning: checking item
                            Warning:   Field `class` contains undefined reference to
                            `http://schema.org/Organization`
cwl/star-genome.cwl:1477:5: Warning: checking object `cwl/star-genome.cwl#dobin@cshl.edu`
                            Warning:   Field `class` contains undefined reference to
                            `http://schema.org/Person`
cwl/star-genome.cwl:1454:3: Warning: Field `class` contains undefined reference to
                            `http://schema.org/SoftwareSourceCode`
cwl/star-genome.cwl:1488:3: Warning: Field `class` contains undefined reference to
                            `http://schema.org/CreativeWork`
cwl/star-genome.cwl:1503:7: Warning: checking item
                            Warning:   Field `class` contains undefined reference to
                            `http://schema.org/Organization`
cwl/star-genome.cwl:1499:5: Warning: checking item
                            Warning:   Field `class` contains undefined reference to
                            `http://schema.org/Organization`
cwl/star-genome.cwl:1493:3: Warning: Field `class` contains undefined reference to
                            `http://schema.org/Person`
Could not load extension schema http://schema.org/docs/schema_org_rdfa.html: Error fetching http://schema.org/docs/schema_org_rdfa.html: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
Warning: Field `$schemas` contains undefined reference to `http://schema.org/docs/schema_org_rdfa.html`
cwl/star-repeatmapping.cwl:1468:5: Warning: Field `class` contains undefined reference to
                                   `http://schema.org/SoftwareApplication`
cwl/star-repeatmapping.cwl:1473:5: Warning: checking object
                                   `http://dx.doi.org/10.1093/bioinformatics/bts635`
                                   Warning:   Field `class` contains undefined reference to
                                   `http://schema.org/ScholarlyArticle`
cwl/star-repeatmapping.cwl:1483:7: Warning: checking item
                                   Warning:   Field `class` contains undefined reference to
                                   `http://schema.org/Organization`
cwl/star-repeatmapping.cwl:1477:5: Warning: checking object
                                   `cwl/star-repeatmapping.cwl#dobin@cshl.edu`
                                   Warning:   Field `class` contains undefined reference to
                                   `http://schema.org/Person`
cwl/star-repeatmapping.cwl:1454:3: Warning: Field `class` contains undefined reference to
                                   `http://schema.org/SoftwareSourceCode`
cwl/star-repeatmapping.cwl:1488:3: Warning: Field `class` contains undefined reference to
                                   `http://schema.org/CreativeWork`
cwl/star-repeatmapping.cwl:1503:7: Warning: checking item
                                   Warning:   Field `class` contains undefined reference to
                                   `http://schema.org/Organization`
cwl/star-repeatmapping.cwl:1499:5: Warning: checking item
                                   Warning:   Field `class` contains undefined reference to
                                   `http://schema.org/Organization`
cwl/star-repeatmapping.cwl:1493:3: Warning: Field `class` contains undefined reference to
                                   `http://schema.org/Person`
[1;30mWARNING[0m [33mWorkflow checker warning:
cwl/wf_trim_and_map_pe.cwl:184:11: Source 'output_trim' of type ["null", {"type": "array", "items":
                                   "File"}] may be incompatible
cwl/wf_trim_and_map_pe.cwl:190:7:    with sink 'input' of type {"type": "array", "items": "File"}
cwl/wf_trim_and_map_pe.cwl:204:11: Source 'output_trim' of type ["null", {"type": "array", "items":
                                   "File"}] may be incompatible
cwl/wf_trim_and_map_pe.cwl:210:7:    with sink 'input_fastqsort_fastq' of type {"type": "array",
                                     "items": "File"}
cwl/wf_trim_and_map_pe.cwl:289:7:  Source 'output_map_unmapped_rev' of type ["null", "File"] may be
                                   incompatible
cwl/wf_trim_and_map_pe.cwl:320:7:    with sink 'srcfile' of type "File"[0m
Could not load extension schema http://schema.org/docs/schema_org_rdfa.html: Error fetching http://schema.org/docs/schema_org_rdfa.html: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
Warning: Field `$schemas` contains undefined reference to `http://schema.org/docs/schema_org_rdfa.html`
cwl/samtools-index.cwl:54:3: Warning: Field `class` contains undefined reference to
                             `http://schema.org/CreativeWork`
cwl/samtools-index.cwl:69:7: Warning: checking item
                             Warning:   Field `class` contains undefined reference to
                             `http://schema.org/Organization`
cwl/samtools-index.cwl:65:5: Warning: checking item
                             Warning:   Field `class` contains undefined reference to
                             `http://schema.org/Organization`
cwl/samtools-index.cwl:59:3: Warning: Field `class` contains undefined reference to
                             `http://schema.org/Person`
Could not load extension schema http://schema.org/docs/schema_org_rdfa.html: Error fetching http://schema.org/docs/schema_org_rdfa.html: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
Warning: Field `$schemas` contains undefined reference to `http://schema.org/docs/schema_org_rdfa.html`
cwl/samtools-viewr2.cwl:225:3: Warning: Field `class` contains undefined reference to
                               `http://schema.org/CreativeWork`
cwl/samtools-viewr2.cwl:240:7: Warning: checking item
                               Warning:   Field `class` contains undefined reference to
                               `http://schema.org/Organization`
cwl/samtools-viewr2.cwl:236:5: Warning: checking item
                               Warning:   Field `class` contains undefined reference to
                               `http://schema.org/Organization`
cwl/samtools-viewr2.cwl:230:3: Warning: Field `class` contains undefined reference to
                               `http://schema.org/Person`
Could not load extension schema http://schema.org/docs/schema_org_rdfa.html: Error fetching http://schema.org/docs/schema_org_rdfa.html: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
Warning: Field `$schemas` contains undefined reference to `http://schema.org/docs/schema_org_rdfa.html`
cwl/samtools-mappedreadnum.cwl:207:3: Warning: Field `class` contains undefined reference to
                                      `http://schema.org/CreativeWork`
cwl/samtools-mappedreadnum.cwl:222:7: Warning: checking item
                                      Warning:   Field `class` contains undefined reference to
                                      `http://schema.org/Organization`
cwl/samtools-mappedreadnum.cwl:218:5: Warning: checking item
                                      Warning:   Field `class` contains undefined reference to
                                      `http://schema.org/Organization`
cwl/samtools-mappedreadnum.cwl:212:3: Warning: Field `class` contains undefined reference to
                                      `http://schema.org/Person`
Could not load extension schema http://schema.org/docs/schema_org_rdfa.html: Error fetching http://schema.org/docs/schema_org_rdfa.html: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
Warning: Field `$schemas` contains undefined reference to `http://schema.org/docs/schema_org_rdfa.html`
cwl/star-genome.cwl:1468:5: Warning: Field `class` contains undefined reference to
                            `http://schema.org/SoftwareApplication`
cwl/star-genome.cwl:1473:5: Warning: checking object
                            `http://dx.doi.org/10.1093/bioinformatics/bts635`
                            Warning:   Field `class` contains undefined reference to
                            `http://schema.org/ScholarlyArticle`
cwl/star-genome.cwl:1483:7: Warning: checking item
                            Warning:   Field `class` contains undefined reference to
                            `http://schema.org/Organization`
cwl/star-genome.cwl:1477:5: Warning: checking object `cwl/star-genome.cwl#dobin@cshl.edu`
                            Warning:   Field `class` contains undefined reference to
                            `http://schema.org/Person`
cwl/star-genome.cwl:1454:3: Warning: Field `class` contains undefined reference to
                            `http://schema.org/SoftwareSourceCode`
cwl/star-genome.cwl:1488:3: Warning: Field `class` contains undefined reference to
                            `http://schema.org/CreativeWork`
cwl/star-genome.cwl:1503:7: Warning: checking item
                            Warning:   Field `class` contains undefined reference to
                            `http://schema.org/Organization`
cwl/star-genome.cwl:1499:5: Warning: checking item
                            Warning:   Field `class` contains undefined reference to
                            `http://schema.org/Organization`
cwl/star-genome.cwl:1493:3: Warning: Field `class` contains undefined reference to
                            `http://schema.org/Person`
Could not load extension schema http://schema.org/docs/schema_org_rdfa.html: Error fetching http://schema.org/docs/schema_org_rdfa.html: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
Warning: Field `$schemas` contains undefined reference to `http://schema.org/docs/schema_org_rdfa.html`
cwl/star-repeatmapping.cwl:1468:5: Warning: Field `class` contains undefined reference to
                                   `http://schema.org/SoftwareApplication`
cwl/star-repeatmapping.cwl:1473:5: Warning: checking object
                                   `http://dx.doi.org/10.1093/bioinformatics/bts635`
                                   Warning:   Field `class` contains undefined reference to
                                   `http://schema.org/ScholarlyArticle`
cwl/star-repeatmapping.cwl:1483:7: Warning: checking item
                                   Warning:   Field `class` contains undefined reference to
                                   `http://schema.org/Organization`
cwl/star-repeatmapping.cwl:1477:5: Warning: checking object
                                   `cwl/star-repeatmapping.cwl#dobin@cshl.edu`
                                   Warning:   Field `class` contains undefined reference to
                                   `http://schema.org/Person`
cwl/star-repeatmapping.cwl:1454:3: Warning: Field `class` contains undefined reference to
                                   `http://schema.org/SoftwareSourceCode`
cwl/star-repeatmapping.cwl:1488:3: Warning: Field `class` contains undefined reference to
                                   `http://schema.org/CreativeWork`
cwl/star-repeatmapping.cwl:1503:7: Warning: checking item
                                   Warning:   Field `class` contains undefined reference to
                                   `http://schema.org/Organization`
cwl/star-repeatmapping.cwl:1499:5: Warning: checking item
                                   Warning:   Field `class` contains undefined reference to
                                   `http://schema.org/Organization`
cwl/star-repeatmapping.cwl:1493:3: Warning: Field `class` contains undefined reference to
                                   `http://schema.org/Person`
[1;30mWARNING[0m [33mWorkflow checker warning:
cwl/wf_trim_and_map_pe.cwl:204:11: Source 'output_trim' of type ["null", {"type": "array", "items":
                                   "File"}] may be incompatible
cwl/wf_trim_and_map_pe.cwl:210:7:    with sink 'input_fastqsort_fastq' of type {"type": "array",
                                     "items": "File"}
cwl/wf_trim_and_map_pe.cwl:289:7:  Source 'output_map_unmapped_rev' of type ["null", "File"] may be
                                   incompatible
cwl/wf_trim_and_map_pe.cwl:320:7:    with sink 'srcfile' of type "File"
cwl/wf_trim_and_map_pe.cwl:184:11: Source 'output_trim' of type ["null", {"type": "array", "items":
                                   "File"}] may be incompatible
cwl/wf_trim_and_map_pe.cwl:190:7:    with sink 'input' of type {"type": "array", "items": "File"}[0m
Could not load extension schema http://schema.org/docs/schema_org_rdfa.html: Error fetching http://schema.org/docs/schema_org_rdfa.html: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
Warning: Field `$schemas` contains undefined reference to `http://schema.org/docs/schema_org_rdfa.html`
cwl/star-genome.cwl:1468:5: Warning: Field `class` contains undefined reference to
                            `http://schema.org/SoftwareApplication`
cwl/star-genome.cwl:1473:5: Warning: checking object
                            `http://dx.doi.org/10.1093/bioinformatics/bts635`
                            Warning:   Field `class` contains undefined reference to
                            `http://schema.org/ScholarlyArticle`
cwl/star-genome.cwl:1483:7: Warning: checking item
                            Warning:   Field `class` contains undefined reference to
                            `http://schema.org/Organization`
cwl/star-genome.cwl:1477:5: Warning: checking object `cwl/star-genome.cwl#dobin@cshl.edu`
                            Warning:   Field `class` contains undefined reference to
                            `http://schema.org/Person`
cwl/star-genome.cwl:1454:3: Warning: Field `class` contains undefined reference to
                            `http://schema.org/SoftwareSourceCode`
cwl/star-genome.cwl:1488:3: Warning: Field `class` contains undefined reference to
                            `http://schema.org/CreativeWork`
cwl/star-genome.cwl:1503:7: Warning: checking item
                            Warning:   Field `class` contains undefined reference to
                            `http://schema.org/Organization`
cwl/star-genome.cwl:1499:5: Warning: checking item
                            Warning:   Field `class` contains undefined reference to
                            `http://schema.org/Organization`
cwl/star-genome.cwl:1493:3: Warning: Field `class` contains undefined reference to
                            `http://schema.org/Person`
Could not load extension schema http://schema.org/docs/schema_org_rdfa.html: Error fetching http://schema.org/docs/schema_org_rdfa.html: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
Warning: Field `$schemas` contains undefined reference to `http://schema.org/docs/schema_org_rdfa.html`
cwl/star-repeatmapping.cwl:1468:5: Warning: Field `class` contains undefined reference to
                                   `http://schema.org/SoftwareApplication`
cwl/star-repeatmapping.cwl:1473:5: Warning: checking object
                                   `http://dx.doi.org/10.1093/bioinformatics/bts635`
                                   Warning:   Field `class` contains undefined reference to
                                   `http://schema.org/ScholarlyArticle`
cwl/star-repeatmapping.cwl:1483:7: Warning: checking item
                                   Warning:   Field `class` contains undefined reference to
                                   `http://schema.org/Organization`
cwl/star-repeatmapping.cwl:1477:5: Warning: checking object
                                   `cwl/star-repeatmapping.cwl#dobin@cshl.edu`
                                   Warning:   Field `class` contains undefined reference to
                                   `http://schema.org/Person`
cwl/star-repeatmapping.cwl:1454:3: Warning: Field `class` contains undefined reference to
                                   `http://schema.org/SoftwareSourceCode`
cwl/star-repeatmapping.cwl:1488:3: Warning: Field `class` contains undefined reference to
                                   `http://schema.org/CreativeWork`
cwl/star-repeatmapping.cwl:1503:7: Warning: checking item
                                   Warning:   Field `class` contains undefined reference to
                                   `http://schema.org/Organization`
cwl/star-repeatmapping.cwl:1499:5: Warning: checking item
                                   Warning:   Field `class` contains undefined reference to
                                   `http://schema.org/Organization`
cwl/star-repeatmapping.cwl:1493:3: Warning: Field `class` contains undefined reference to
                                   `http://schema.org/Person`
[1;30mWARNING[0m [33mWorkflow checker warning:
cwl/wf_trim_and_map_pe.cwl:204:11: Source 'output_trim' of type ["null", {"type": "array", "items":
                                   "File"}] may be incompatible
cwl/wf_trim_and_map_pe.cwl:210:7:    with sink 'input_fastqsort_fastq' of type {"type": "array",
                                     "items": "File"}
cwl/wf_trim_and_map_pe.cwl:289:7:  Source 'output_map_unmapped_rev' of type ["null", "File"] may be
                                   incompatible
cwl/wf_trim_and_map_pe.cwl:320:7:    with sink 'srcfile' of type "File"
cwl/wf_trim_and_map_pe.cwl:184:11: Source 'output_trim' of type ["null", {"type": "array", "items":
                                   "File"}] may be incompatible
cwl/wf_trim_and_map_pe.cwl:190:7:    with sink 'input' of type {"type": "array", "items": "File"}[0m
Could not load extension schema http://schema.org/docs/schema_org_rdfa.html: Error fetching http://schema.org/docs/schema_org_rdfa.html: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
Warning: Field `$schemas` contains undefined reference to `http://schema.org/docs/schema_org_rdfa.html`
cwl/samtools-index.cwl:54:3: Warning: Field `class` contains undefined reference to
                             `http://schema.org/CreativeWork`
cwl/samtools-index.cwl:69:7: Warning: checking item
                             Warning:   Field `class` contains undefined reference to
                             `http://schema.org/Organization`
cwl/samtools-index.cwl:65:5: Warning: checking item
                             Warning:   Field `class` contains undefined reference to
                             `http://schema.org/Organization`
cwl/samtools-index.cwl:59:3: Warning: Field `class` contains undefined reference to
                             `http://schema.org/Person`
Could not load extension schema http://schema.org/docs/schema_org_rdfa.html: Error fetching http://schema.org/docs/schema_org_rdfa.html: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
Warning: Field `$schemas` contains undefined reference to `http://schema.org/docs/schema_org_rdfa.html`
cwl/samtools-viewr2.cwl:225:3: Warning: Field `class` contains undefined reference to
                               `http://schema.org/CreativeWork`
cwl/samtools-viewr2.cwl:240:7: Warning: checking item
                               Warning:   Field `class` contains undefined reference to
                               `http://schema.org/Organization`
cwl/samtools-viewr2.cwl:236:5: Warning: checking item
                               Warning:   Field `class` contains undefined reference to
                               `http://schema.org/Organization`
cwl/samtools-viewr2.cwl:230:3: Warning: Field `class` contains undefined reference to
                               `http://schema.org/Person`
Could not load extension schema http://schema.org/docs/schema_org_rdfa.html: Error fetching http://schema.org/docs/schema_org_rdfa.html: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
Warning: Field `$schemas` contains undefined reference to `http://schema.org/docs/schema_org_rdfa.html`
cwl/samtools-mappedreadnum.cwl:207:3: Warning: Field `class` contains undefined reference to
                                      `http://schema.org/CreativeWork`
cwl/samtools-mappedreadnum.cwl:222:7: Warning: checking item
                                      Warning:   Field `class` contains undefined reference to
                                      `http://schema.org/Organization`
cwl/samtools-mappedreadnum.cwl:218:5: Warning: checking item
                                      Warning:   Field `class` contains undefined reference to
                                      `http://schema.org/Organization`
cwl/samtools-mappedreadnum.cwl:212:3: Warning: Field `class` contains undefined reference to
                                      `http://schema.org/Person`
[1;30mWARNING[0m [33mWorkflow checker warning:
cwl/wf_get_peaks_pe.cwl:397:7: 'species' is not an input parameter of
                               file:///groups/cgsd/alexandre/eclip/workflow/cwl/wf_clipseqcore_pe_2barcodes.cwl,
                               expected barcodesfasta, chrom_sizes, dataset, randomer_length, read,
                               repeatElementGenomeDir, speciesGenomeDir
cwl/wf_get_peaks_pe.cwl:471:7: 'species' is not an input parameter of
                               file:///groups/cgsd/alexandre/eclip/workflow/cwl/wf_clipseqcore_pe_1barcode.cwl,
                               expected barcodesfasta, chrom_sizes, dataset, randomer_length, read,
                               repeatElementGenomeDir, speciesGenomeDir[0m
```

**Comment by alexmondaini** [comment]
also many perl locale issues, thought `locale` wouldn't be a issue since the it's using the locale inside the container right ?

```
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
perl: warning: Falling back to the standard locale ("C").
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
perl: warning: Falling back to the standard locale ("C").
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
perl: warning: Falling back to the standard locale ("C").
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
perl: warning: Falling back to the standard locale ("C").
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
perl: warning: Falling back to the standard locale ("C").
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
perl: warning: Falling back to the standard locale ("C").
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
perl: warning: Falling back to the standard locale ("C").
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
perl: warning: Falling back to the standard locale ("C").
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
perl: warning: Falling back to the standard locale ("C").
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
perl: warning: Falling back to the standard locale ("C").
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
perl: warning: Falling back to the standard locale ("C").
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
perl: warning: Falling back to the standard locale ("C").
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
perl: warning: Falling back to the standard locale ("C").
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
perl: warning: Falling back to the standard locale ("C").
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
perl: warning: Falling back to the standard locale ("C").
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
perl: warning: Falling back to the standard locale ("C").
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
perl: warning: Falling back to the standard locale ("C").
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
perl: warning: Falling back to the standard locale ("C").
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
perl: warning: Falling back to the standard locale ("C").
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
perl: warning: Falling back to the standard locale ("C").
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
perl: warning: Falling back to the standard locale ("C").
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
perl: warning: Falling back to the standard locale ("C").
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
perl: warning: Falling back to the standard locale ("C").
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
perl: warning: Falling back to the standard locale ("C").
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
perl: warning: Falling back to the standard locale ("C").
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
perl: warning: Falling back to the standard locale ("C").
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
perl: warning: Falling back to the standard locale ("C").
```

**Comment by alexmondaini** [comment]
Hi Brian,

sorry to bother you with so many questions. I don't need to demultiplex my fastqs and I noticed that you have a different cwl file for nodemux. Do you think if I change this file `https://github.com/YeoLab/eclip/blob/master/cwl/wf_get_peaks_pe.cwl` at `steps` from:

```
steps:

###########################################################################
# Upstream
###########################################################################

  step_ip_alignment:
    run: wf_clipseqcore_pe_2barcodes.cwl
```

to this :

steps:

###########################################################################
# Upstream
###########################################################################

  step_ip_alignment:
    run: wf_clipseqcore_pe_2barcodes_nodemux.cwl

I am good to go using the pipeline without demultiplexing ??? thanks a lot.

**Comment by byee4** [comment]
It seems like there is a broken link, thanks for pointing that out! It shouldn't affect the results and your data should process fine with those warnings. Same with the Perl warnings, I haven't seen those affect results at all but happy to look into it further.

I don't think nodemux works yet for PE, that file was something I started but haven't finished. The demultiplexing step for PE was built into the randomer/UMI assignment and harder to separate. That might not apply to you if you're also not worried about PCR dedup, but both steps are part of our standard workflow that's what is automated/supported. 

So I can't officially endorse this as dedup is generally what we recommend here, but maybe I can help provide hints to get what you need (skip demux and dup removal):

First, you'll need to ensure your read headers have this format:

```
@NAATAACAAA:K00180:248:HCT55BBXX:3:1101:8511:1050 1:N:0:NCCGGAGA+NCAGAGCC
CTGGAACGGGGATGCTTGCATGTGTAATCTTACT
+
JJJJJJJFJJJJJJFJJJJJJJJJJJJJJJJJAJ
```

Where "`NAATAACAAA`" indicates the randomer that this script will use to perform deduplication. Making this really long should reduce the chance of collisions, effectively "cancelling" the barcode collapsing step. 

https://github.com/YeoLab/eclip/blob/93e5517f1fdbad1073bcc4c0bfd84d24c5cdf10b/bin/barcodecollapsepe.py#L83

Next, you'll need to run this CWL, but keep in mind that the manifest/config file will look a bit different. This subworkflow starts downstream of the demux step and will trim and map your reads, as well as perform the collapsing above. This means that you'll be running it for each inline barcode.

https://github.com/YeoLab/eclip/blob/master/cwl/wf_trim_and_map_pe.cwl

The `X_output_sorted_bam` for each inline barcode can then be merged and R1-filtered (see these steps from the SOP):

Samtools  merge (PE only): Takes inputs from multiple final bam files.  Merges the two technical replicates for further downstream analysis.  

`samtools  merge EXAMPLE_PE.rep2_clip.C01.r1.fq.genome-mappedSo.rmDupSo.merged.bam EXAMPLE_PE.rep2_clip.C01.r1.fq.genome-mappedSo.rmDupSo.bam EXAMPLE_PE.rep2_clip.D8f.r1.fq.genome-mappedSo.rmDupSo.bam`

Samtools index: Takes output from sortSam, makes bam index for use downstream.  
`samtools  index  EXAMPLE_PE.rep2_clip.C01.r1.fq.genome-mappedSo.rmDupSo.merged.bam  
`
Samtools view (PE only):  Takes output from samtools merge.  Only outputs the second read in each pair for use with a single stranded peak caller.  This is the final bam file to perform analysis on.  

`samtools view -f 128 -b -o EXAMPLE_PE.rep2_clip.C01.r1.fq.genome-mappedSo.rmDupSo.merged.r2.bam EXAMPLE_PE.rep2_clip.C01.r1.fq.genome-mappedSo.rmDupSo.merged.bam`

The merged BAM file will be what you'll use to run Clipper with.
