### ISSUE TITLE
Help with demo prerequisite files

### ISSUE THREAD

**Issue by valerieT1998** [YeoLab/eclip#37]
Hi,
when I tried testing this pipeline using the demo in the READMe, an error occurred:
"
URI prefix 's' of 's:Organization' not recognized, are you missing a $namespaces section?
URI prefix 's' of 's:name' not recognized, are you missing a $namespaces section?
URI prefix 's' of 's:Organization' not recognized, are you missing a $namespaces section?
samtools-mappedreadnum.cwl:197:3:   Unsupported scheme in url: s:CreativeWork
samtools-mappedreadnum.cwl:212:7:   checking item
samtools-mappedreadnum.cwl:212:7:     Unsupported scheme in url: s:Organization
samtools-mappedreadnum.cwl:208:5:   checking item
samtools-mappedreadnum.cwl:208:5:     Unsupported scheme in url: s:Organization
samtools-mappedreadnum.cwl:202:3:   Unsupported scheme in url: s:Person
Traceback (most recent call last):
  File "/shared/tools/eCLIP_env/bin/cwltool", line 8, in <module>
    sys.exit(main())
  File "/shared/tools/eCLIP_env/lib/python2.7/site-packages/cwltool/main.py", line 566, in main
    input_basedir=input_basedir)
  File "/shared/tools/eCLIP_env/lib/python2.7/site-packages/cwltool/main.py", line 246, in init_job_order
    normalizeFilesDirs(job_order_object)
  File "/shared/tools/eCLIP_env/lib/python2.7/site-packages/cwltool/pathmapper.py", line 91, in normalizeFilesDirs
    visit_class(job, ("File", "Directory"), addLocation)
  File "/shared/tools/eCLIP_env/lib/python2.7/site-packages/cwltool/pathmapper.py", line 48, in visit_class
    visit_class(rec[d], cls, op)
  File "/shared/tools/eCLIP_env/lib/python2.7/site-packages/cwltool/pathmapper.py", line 46, in visit_class
    op(rec)
  File "/shared/tools/eCLIP_env/lib/python2.7/site-packages/cwltool/pathmapper.py", line 67, in addLocation
    raise validate.ValidationException("Anonymous file object must have 'contents' and 'basename' fields.")
schema_salad.validate.ValidationException: Anonymous file object must have 'contents' and 'basename' fields.
"
I'm not quite sure what is causing this issue.
Could it be related to the Star  indices input files... The RepBase directory contains a homo_sapiens_repBase.fasta (from here https://github.com/YeoLab/eCLIP/issues/27)  file and for StarIndex directory, UCSC's hg19.fa file. 

thanks

**Comment by byee4** [comment]
Hi,

I don’t think the fasta files should interfere with the pipeline, as long as the indices are being built properly, the step should run okay. I’m guessing that the runtime environment being Python2 may have something to do with the error? I know this is a bit tricky, since one or two softwares were built with Python2 in mind, but the pipeline itself should be run in a Python3 environment, and run those Python2 steps (eg. CLIPper) inside its own Singularity container.

Is this test run performed on AWS using the “Zero to Peaks” documentation?

SECURE: MESSAGE FROM Valerie Triassi ON 4/17/23, 12:05 PM


Hi,
when I tried testing this pipeline using the demo in the READMe, an error occurred:
URI prefix 's' of 's:Organization' not recognized, are you missing a $namespaces section? URI prefix 's' of 's:name' not recognized, are you missing a $namespaces section? URI prefix 's' of 's:Organization' not recognized, are you missing a $namespaces section? samtools-mappedreadnum.cwl:197:3: Unsupported scheme in url: s:CreativeWork samtools-mappedreadnum.cwl:212:7: checking item samtools-mappedreadnum.cwl:212:7: Unsupported scheme in url: s:Organization samtools-mappedreadnum.cwl:208:5: checking item samtools-mappedreadnum.cwl:208:5: Unsupported scheme in url: s:Organization samtools-mappedreadnum.cwl:202:3: Unsupported scheme in url: s:Person Traceback (most recent call last): File "/shared/tools/eCLIP_env/bin/cwltool", line 8, in <module> sys.exit(main()) File "/shared/tools/eCLIP_env/lib/python2.7/site-packages/cwltool/main.py", line 566, in main input_basedir=input_basedir) File "/shared/tools/eCLIP_env/lib/python2.7/site-packages/cwltool/main.py", line 246, in init_job_order normalizeFilesDirs(job_order_object) File "/shared/tools/eCLIP_env/lib/python2.7/site-packages/cwltool/pathmapper.py", line 91, in normalizeFilesDirs visit_class(job, ("File", "Directory"), addLocation) File "/shared/tools/eCLIP_env/lib/python2.7/site-packages/cwltool/pathmapper.py", line 48, in visit_class visit_class(rec[d], cls, op) File "/shared/tools/eCLIP_env/lib/python2.7/site-packages/cwltool/pathmapper.py", line 46, in visit_class op(rec) File "/shared/tools/eCLIP_env/lib/python2.7/site-packages/cwltool/pathmapper.py", line 67, in addLocation raise validate.ValidationException("Anonymous file object must have 'contents' and 'basename' fields.") schema_salad.validate.ValidationException: Anonymous file object must have 'contents' and 'basename' fields.
I'm not quite sure what is causing this issue.
Could it be related to the Star indices input files... The RepBase directory contains a homo_sapiens_repBase.fasta (from here #27<https://urldefense.com/v3/__https:/github.com/YeoLab/eCLIP/issues/27__;!!LLK065n_VXAQ!kVYlsHMyYQnE93pexahCLBnlemW7UZIA2bCFDQ2Xpuungj2LSmvdvbO3cLdk34Kpai4NhA8J8TK53maWbsr45QHXrot5$>) file and for StarIndex directory, UCSC's hg19.fa file.

thanks
