### ISSUE TITLE
Problem for Demultiplexing paired-end reads

### ISSUE THREAD

**Issue by FionaMoon** [YeoLab/eclip#38]
Hi eCLIP team,
I try to using this pipline for GSE177848 ,but got error when running eclipdemux.
I rarely use python so it's hard for me to figure out this problem.

My code and error as follow:
```
eclipdemux \
--metrics exp_PE.rep1_eclip.---.--.metrics \
--expectedbarcodeida C01 \
--expectedbarcodeidb D8f \
--fastq_1 ./experiment/rep1/R1_ENCFF010ECT.fastq.gz \
--fastq_2 ./experiment/rep1/R2_ENCFF795GKY.fastq.gz \
--newname rep1_clip \
--dataset exp_PE \
--barcodesfile /p300s/fangxd_group/liangyue/skipper/adapter/yeolabbarcodes_20170101.fasta \
--length 5
```
> Traceback (most recent call last):
  File "/xtdisk/fangxd_group/liangyue/miniconda/envs/eCLIP/bin/eclipdemux", line 33, in <module>
    sys.exit(load_entry_point('eclipdemux-distribution==0.0.1', 'console_scripts', 'eclipdemux')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/miniconda/envs/eCLIP/lib/python3.11/site-packages/eclipdemux_distribution-0.0.1-py3.11.egg/eclipdemux_package/demux.py", line 918, in main
    datastructure_setup(
  File "/home/miniconda/envs/eCLIP/lib/python3.11/site-packages/eclipdemux_distribution-0.0.1-py3.11.egg/eclipdemux_package/demux.py", line 764, in datastructure_setup
    barcodedict = barcodedict_create(barcodesfile)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/miniconda/envs/eCLIP/lib/python3.11/site-packages/eclipdemux_distribution-0.0.1-py3.11.egg/eclipdemux_package/demux.py", line 235, in barcodedict_create
    barcodedict = _barcodedict_from_fastaio(fastaio)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/miniconda/envs/eCLIP/lib/python3.11/site-packages/eclipdemux_distribution-0.0.1-py3.11.egg/eclipdemux_package/demux.py", line 179, in _barcodedict_from_fastaio
    _assert_legal_barcodeseq(barcodeseq)
  File "/home/miniconda/envs/eCLIP/lib/python3.11/site-packages/eclipdemux_distribution-0.0.1-py3.11.egg/eclipdemux_package/demux.py", line 146, in _assert_legal_barcodeseq
    raise_with_traceback(IllegalBarcodeSeqValueError(barcodeseq))
  File "/home/miniconda/envs/eCLIP/lib/python3.11/site-packages/future/utils/__init__.py", line 449, in raise_with_traceback
    raise exc.with_traceback(traceback)
eclipdemux_package.demux.IllegalBarcodeSeqValueError

Thank you for your help!

**Comment by byee4** [comment]
Hello,

If downloading from the ENCODE project, the DCC required all peCLIP<https://www.nature.com/articles/nmeth.3810https:/www.nature.com/articles/nmeth.3810> files to be demultiplexed prior to submission, so the demultiplexing step is not needed. You can proceed with the next steps as long as your pre-processed read contains the UMI (in red). Note that for seCLIP<https://link.springer.com/protocol/10.1007/978-1-4939-7204-3_14>, the UMIs are handled by umi_tools<https://github.com/CGATOxford/UMI-tools>, therefore the location in the fastq header will be different.


@NGTCTGGCTT:K00180:223:HCLHCBBXX:7:1101:25834:998 1:N:0:NTTCAGAA+NTTCGCCT

GATCTATGACCCCGCTGCGCCAGGTTCCCCACGAACGTGCGNTG

+

JJFJFJJJJJJJJJJJJJJJJJJJJJJFAJJJFJJJJJ<JJ#JJ


From: LY ***@***.***>
Date: Monday, July 3, 2023 at 1:48 AM
To: YeoLab/eCLIP ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [YeoLab/eCLIP] Error for Demultiplexes paired-end reads (Issue #38)

Hi eCLIP team,
I try to using this pipline for GSE177848 ,but got error when running eclipdemux.
I rarely use python so it's hard for me to figure out this problem.

My code and error as follow:

eclipdemux \

--metrics exp_PE.rep1_eclip.---.--.metrics \

--expectedbarcodeida C01 \

--expectedbarcodeidb D8f \

--fastq_1 ./experiment/rep1/R1_ENCFF010ECT.fastq.gz \

--fastq_2 ./experiment/rep1/R2_ENCFF795GKY.fastq.gz \

--newname rep1_clip \

--dataset exp_PE \

--barcodesfile /p300s/fangxd_group/liangyue/skipper/adapter/yeolabbarcodes_20170101.fasta \

--length 5

Traceback (most recent call last):
File "/xtdisk/fangxd_group/liangyue/miniconda/envs/eCLIP/bin/eclipdemux", line 33, in
sys.exit(load_entry_point('eclipdemux-distribution==0.0.1', 'console_scripts', 'eclipdemux')())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/miniconda/envs/eCLIP/lib/python3.11/site-packages/eclipdemux_distribution-0.0.1-py3.11.egg/eclipdemux_package/demux.py", line 918, in main
datastructure_setup(
File "/home/miniconda/envs/eCLIP/lib/python3.11/site-packages/eclipdemux_distribution-0.0.1-py3.11.egg/eclipdemux_package/demux.py", line 764, in datastructure_setup
barcodedict = barcodedict_create(barcodesfile)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/miniconda/envs/eCLIP/lib/python3.11/site-packages/eclipdemux_distribution-0.0.1-py3.11.egg/eclipdemux_package/demux.py", line 235, in barcodedict_create
barcodedict = _barcodedict_from_fastaio(fastaio)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/miniconda/envs/eCLIP/lib/python3.11/site-packages/eclipdemux_distribution-0.0.1-py3.11.egg/eclipdemux_package/demux.py", line 179, in _barcodedict_from_fastaio
_assert_legal_barcodeseq(barcodeseq)
File "/home/miniconda/envs/eCLIP/lib/python3.11/site-packages/eclipdemux_distribution-0.0.1-py3.11.egg/eclipdemux_package/demux.py", line 146, in _assert_legal_barcodeseq
raise_with_traceback(IllegalBarcodeSeqValueError(barcodeseq))
File "/home/miniconda/envs/eCLIP/lib/python3.11/site-packages/future/utils/init.py", line 449, in raise_with_traceback
raise exc.with_traceback(traceback)
eclipdemux_package.demux.IllegalBarcodeSeqValueError

Thank you for your help!

**Comment by FionaMoon** [comment]
Thank you for your answer!
I still have a question for UMI extraction for peCLIP.

Whether umi_tools can only be used for seCLIP? I've learned that umi_tools can be used for pair-end reads like this:
```
# For paired end reads, the following reads end one from stdin and end two from FASTQIN and outputs end one to stdout and end two to FASTQOUT:

umi_tools extract --extract-method=string
--bc-pattern=[PATTERN] --bc-pattern2=[PATTERN]
--read2-in=[FASTQIN] --read2-out=[FASTQOUT] -L extract.log [OPTIONS]
```

So, I wonder if it's okay to use the pair-end mode of umi_tools for UMI extraction of peCLIP.

**Comment by byee4** [comment]
Hi,

Yes it’s fine to use umi_tools to extract UMIs from peCLIP, as long as you are aware that:

  *   The peCLIP describes reads that contain both a UMI and an inline barcode sequence, used to demultiplex technical replicates, but data downloaded from the encodeproject.org site should be already demultiplexed.
  *   Data downloaded from encodeproject should already have the UMI embedded in the read header (see red seq below) in a location that is not default to umi_tools.
  *   You’ll also use umi_tools to perform the deduplication instead of our own barcodecollapse perl script

We had recommended using the eclipdemux package since we also were writing our own UMI collapsing script, but more robust tools have since come out.

RBFOX2 (K562) downloaded from encodeproject.org:


@NTCCAAATCA:K00180:175:H7W2CBBXX:6:1101:11150:1050 1:N:0:NAATTCGT+NCAGAGCC

GTCCTTTATCTCGACATTGAATCTTTCCAGTGTATCGAGTGGCCT

+

JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ


From: LY ***@***.***>
Date: Thursday, July 6, 2023 at 6:35 PM
To: YeoLab/eCLIP ***@***.***>
Cc: Brian Yee ***@***.***>, Comment ***@***.***>
Subject: Re: [YeoLab/eCLIP] Problem for Demultiplexing paired-end reads (Issue #38)

Thank you for your answer!
I still have a question for UMI extraction for peCLIP.

Whether umi_tools can only be used for seCLIP? I've learned that umi_tools can be used for pair-end reads like this:

# For paired end reads, the following reads end one from stdin and end two from FASTQIN and outputs end one to stdout and end two to FASTQOUT:



umi_tools extract --extract-method=string

--bc-pattern=[PATTERN] --bc-pattern2=[PATTERN]

--read2-in=[FASTQIN] --read2-out=[FASTQOUT] -L extract.log [OPTIONS]

So, I wonder if it's okay to use the pair-end mode of umi_tools for UMI extraction of peCLIP.

**Comment by FionaMoon** [comment]
Thanks for your clear explaination!
